// File generated by FlutterFire CLI.
// Mock Firebase options for local scaffolding.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with Firebase services.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'mock-api-key-web-customer-12345',
    appId: '1:1234567890:web:customerappstub',
    messagingSenderId: '1234567890',
    projectId: 'zepto-clone-customer',
    authDomain: 'zepto-clone-customer.firebaseapp.com',
    storageBucket: 'zepto-clone-customer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'mock-api-key-android-customer-12345',
    appId: '1:1234567890:android:customerappstub',
    messagingSenderId: '1234567890',
    projectId: 'zepto-clone-customer',
    storageBucket: 'zepto-clone-customer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'mock-api-key-ios-customer-12345',
    appId: '1:1234567890:ios:customerappstub',
    messagingSenderId: '1234567890',
    projectId: 'zepto-clone-customer',
    storageBucket: 'zepto-clone-customer.appspot.com',
    iosBundleId: 'com.zepto.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'mock-api-key-macos-customer-12345',
    appId: '1:1234567890:ios:customerappstub',
    messagingSenderId: '1234567890',
    projectId: 'zepto-clone-customer',
    storageBucket: 'zepto-clone-customer.appspot.com',
    iosBundleId: 'com.zepto.customerApp.macos',
  );
}
